class BNB_FA_JPN_Medic_Jeitai_D : BNB_FA_JPN_Rifleman_Jeitai_D {
	displayName = "Medic";
	// editorPreview = "\x\bnb_fa\norwegian_armed_forces\data\preview\BNB_FA_JPN_Medic_Jeitai_D.jpg";
	icon = "iconManMedic";
	picture = "pictureHeal";

	attendant = 1;

	bnb_fa_weaponItems[] = {"","","rhsusf_acc_compm4",""};

	uniformClass = "Japan_JP_Jeitai_Uniform_D";

	backpack = "Japan_JP_Jeitai_Desert_Kitbag";

	weapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};
	respawnWeapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};

	magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};

	items[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
	respawnItems[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};

	linkedItems[] = {"V_Deltaforce_Desert_Jeitai","Japan_JP_Jeitai_D_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
	respawnLinkedItems[] = {"V_Deltaforce_Desert_Jeitai","Japan_JP_Jeitai_D_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
};

class BNB_FA_JPN_Medic_Winter : BNB_FA_JPN_Medic_Jeitai_D {
	displayName = "Medic";
	// editorPreview = 
	icon = "iconManMedic";
	picture = "pictureHeal";

	attendant = 1;

	bnb_fa_weaponItems[] = {};

	uniformClass = "Japan_JP_Pattern_Uniform_Digital";

	backpack = "Japan_JP_Pattern_Digital_Kitbag";

	weapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};
	respawnWeapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};

	magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};

	items[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
	respawnItems[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};

	linkedItems[] = {"V_Deltaforce_Pattern_Digital","Japan_JP_Pattern_Digital_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
	respawnLinkedItems[] = {"V_Deltaforce_Pattern_Digital","Japan_JP_Pattern_Digital_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
};

class BNB_FA_JPN_Medic_Navy : BNB_FA_JPN_Rifleman_Navy {
	displayName = "Medic";
	// editorPreview = "\x\bnb_fa\norwegian_armed_forces\data\preview\BNB_FA_BW2_Medic_Multi.jpg";
	icon = "iconManMedic";
	picture = "pictureHeal";

	attendant = 1;

	bnb_fa_weaponItems[] = {"","","rhsusf_acc_compm4",""};

	uniformClass = "Japan_JP_Pattern_Uniform_Navy";

	backpack = "Japan_JP_Pattern_Navy_Kitbag";

	weapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};
	respawnWeapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};

	magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red"};

	items[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
	respawnItems[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};

	linkedItems[] = {"V_Deltaforce_Pattern_Navy","Japan_JP_Pattern_Navy_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
	respawnLinkedItems[] = {"V_Deltaforce_Pattern_Navy","Japan_JP_Pattern_Navy_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
};

class BNB_FA_JPN_Medic_Jeitai : BNB_FA_JPN_Rifleman_Jeitai {
	displayName = "Medic";
	// editorPreview = "\x\bnb_fa\norwegian_armed_forces\data\preview\BNB_FA_BW2_Medic_Fleck.jpg";
	icon = "iconManMedic";
	picture = "pictureHeal";

	attendant = 1;

	bnb_fa_weaponItems[] = {"","","rhsusf_acc_compm4",""};

	uniformClass = "Japan_JP_Jeitai_Uniform";

	backpack = "Japan_JP_Jeitai_Kitbag";

	weapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};
	respawnWeapons[] = {"rhs_weap_hk416d10","sp_fwa_l9a1_hipower_wood","Throw","Put"};

	magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue"};
	respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","sp_fwa_13Rnd_9mm_HiPower","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","rhs_mag_30Rnd_556x45_M855A1_PMAG_Tracer_red","SmokeShell","SmokeShell","SmokeShell","SmokeShell","HandGrenade","HandGrenade","SmokeShellGreen","SmokeShellBlue"};

	items[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};
	respawnItems[] = {"ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_adenosine","ACE_CableTie","ACE_CableTie","ACE_EarPlugs","ACE_epinephrine","ACE_epinephrine","ACE_IR_Strobe_Item","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_tourniquet","ACE_MapTools","ACE_Flashlight_XL50","ACE_surgicalKit","ACE_EntrenchingTool","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_elasticBandage","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_250","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_bloodIV_500","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_adenosine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_epinephrine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_morphine","ACE_tourniquet","ACE_tourniquet","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage","ACE_packingBandage"};

	linkedItems[] = {"V_Deltaforce_Jeitai","Japan_JP_Jeitai_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
	respawnLinkedItems[] = {"V_Deltaforce_Jeitai","Japan_JP_Jeitai_Helmet","ItemMap","ItemCompass","ACE_Altimeter","TFAR_anprc152","ItemGPS"};
};
